name: GitHub Micsci
on:
  push:
    branches:
      -main
jobs:
  Explore-Github-Actions:
    runs-on: Ubuntu-latest
    steps:
      -name: Checkout code
      uses: action/checkout@v3
      
run: echo "Je suis le boss"
